/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#20201f",
        "surface-tint": "#c6c6c6",
        "secondary": "#ffb1c4",
        "outline-variant": "#4c4546",
        "surface-container-lowest": "#0e0e0e",
        "inverse-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "on-primary-fixed-variant": "#474747",
        "primary-container": "#000000",
        "background": "#131313",
        "on-primary-fixed": "#1b1b1b",
        "surface": "#131313",
        "primary-fixed": "#e2e2e2",
        "primary": "#c6c6c6",
        "on-primary": "#303030",
        "on-primary-container": "#757575",
        "on-tertiary-container": "#747576",
        "on-surface": "#e5e2e1",
        "primary-fixed-dim": "#c6c6c6",
        "inverse-on-surface": "#313030",
        "secondary-fixed": "#ffd9e1",
        "on-error": "#690005",
        "surface-container-low": "#1c1b1b",
        "tertiary-container": "#000000",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#3f001a",
        "secondary-fixed-dim": "#ffb1c4",
        "outline": "#988e90",
        "surface-variant": "#353535",
        "surface-bright": "#393939",
        "surface-container-high": "#2a2a2a",
        "on-secondary-container": "#590028",
        "error-container": "#93000a",
        "surface-dim": "#131313",
        "tertiary-fixed-dim": "#c6c6c7",
        "error": "#ffb4ab",
        "on-secondary": "#65002e",
        "on-tertiary": "#2f3131",
        "tertiary-fixed": "#e2e2e2",
        "on-surface-variant": "#cfc4c5",
        "tertiary": "#c6c6c7",
        "secondary-container": "#ff4a8d",
        "hot-pink": "#ff007f",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-container-highest": "#353535",
        "inverse-primary": "#5e5e5e",
        "on-tertiary-fixed-variant": "#454747",
        "on-secondary-fixed-variant": "#8f0044"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.375rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "24px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "stack-lg": "48px",
        "unit": "4px",
        "stack-sm": "12px"
      },
      fontFamily: {
        "display-lg": ["Anton", "sans-serif"],
        "stat-lg": ["Anton", "sans-serif"],
        "headline-lg-mobile": ["Anton", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Anton", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Anton", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["80px", { "lineHeight": "80px", "letterSpacing": "2px", "fontWeight": "400" }],
        "stat-lg": ["36px", { "lineHeight": "40px", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "36px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "1.5px", "fontWeight": "700" }],
        "headline-lg": ["48px", { "lineHeight": "52px", "letterSpacing": "1px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "28px", "fontWeight": "400" }]
      },
      boxShadow: {
        "neon": "0 0 15px 0px rgba(255, 74, 141, 0.35)",
        "neon-lg": "0 0 25px 5px rgba(255, 74, 141, 0.5)",
        "neon-intense": "0 0 30px rgba(255, 0, 127, 0.6)"
      }
    },
  },
  plugins: [],
}
