-- NutriFuel Database Schema Setup
-- Run this in your Supabase SQL Editor to create tables and seed default data.

-- 1. Drop existing tables if they exist (clean setup)
DROP TABLE IF EXISTS invoices CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS meals CASCADE;
DROP TABLE IF EXISTS nutritionists CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2. Create Nutritionists Table
CREATE TABLE nutritionists (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT,
    specialty TEXT,
    experience TEXT,
    rating NUMERIC(3, 2),
    reviews_count INTEGER,
    clients_trained INTEGER,
    avatar TEXT,
    banner TEXT,
    bio TEXT,
    certifications JSONB DEFAULT '[]'::jsonb,
    philosophy TEXT,
    specialized_programs JSONB DEFAULT '[]'::jsonb,
    recent_reviews JSONB DEFAULT '[]'::jsonb
);

-- 3. Create Users Table
CREATE TABLE users (
    email TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    membership TEXT DEFAULT 'Free Tier',
    member_since TEXT,
    age INTEGER,
    weight INTEGER,
    height TEXT,
    target_weight INTEGER,
    daily_calories_target INTEGER DEFAULT 2000,
    protein_target INTEGER DEFAULT 150,
    carbs_target INTEGER DEFAULT 200,
    fats_target INTEGER DEFAULT 65,
    water_target_oz INTEGER DEFAULT 128,
    water_consumed_oz INTEGER DEFAULT 0,
    assigned_nutritionist_id TEXT REFERENCES nutritionists(id) ON DELETE SET NULL,
    active_plan TEXT,
    role TEXT DEFAULT 'USER'
);

-- 4. Create Meals Table
CREATE TABLE meals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT REFERENCES users(email) ON DELETE CASCADE,
    name TEXT NOT NULL,
    time TEXT,
    calories INTEGER DEFAULT 0,
    protein INTEGER DEFAULT 0,
    carbs INTEGER DEFAULT 0,
    fats INTEGER DEFAULT 0,
    completed BOOLEAN DEFAULT false,
    date DATE DEFAULT CURRENT_DATE
);

-- 5. Create Bookings Table
CREATE TABLE bookings (
    id TEXT PRIMARY KEY,
    user_email TEXT REFERENCES users(email) ON DELETE CASCADE,
    nutritionist_id TEXT REFERENCES nutritionists(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    goals TEXT,
    status TEXT DEFAULT 'Confirmed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. Create Invoices Table
CREATE TABLE invoices (
    id TEXT PRIMARY KEY,
    user_email TEXT REFERENCES users(email) ON DELETE CASCADE,
    date TEXT NOT NULL,
    plan TEXT NOT NULL,
    amount TEXT NOT NULL,
    status TEXT DEFAULT 'PAID',
    method TEXT NOT NULL
);

-- Disable Row Level Security (RLS) for simple prototype development.
-- (In production, you would configure RLS policies for each table)
ALTER TABLE nutritionists DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE meals DISABLE ROW LEVEL SECURITY;
ALTER TABLE bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;


-- ==========================================
-- SEED DATA INJECTIONS
-- ==========================================

-- Seed Nutritionists
INSERT INTO nutritionists (id, name, title, specialty, experience, rating, reviews_count, clients_trained, avatar, banner, bio, certifications, philosophy, specialized_programs, recent_reviews)
VALUES 
(
    'sarah-jenkins',
    'Dr. Sarah Jenkins, RD, CSSD',
    'Chief Performance Dietitian',
    'Endurance, Recovery & Glycemic Optimization',
    '12+ Years',
    4.9,
    142,
    850,
    'https://images.unsplash.com/photo-1594824813591-2394d2146f48?auto=format&fit=crop&w=600&q=80',
    'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
    'Former Olympic conditioning consultant with a doctorate in Metabolic Bioenergetics from Stanford. Dr. Jenkins specializes in high-output athlete periodization, gut microbiome resilience, and intra-workout nutrient delivery for peak aerobic and anaerobic performance.',
    '["Doctor of Clinical Nutrition (DCN)", "Board Certified Specialist in Sports Dietetics (CSSD)", "ISSN Certified Sports Nutritionist (CISSN)", "American College of Sports Medicine (ACSM)"]'::jsonb,
    'We do not prescribe generic diet fads. Every milligram of carbohydrate and microgram of electrolyte is calculated to maximize muscular output and mitochondrial density.',
    '[{"name": "Endurance Glycogen Supercompensation", "duration": "12 Weeks", "intensity": "Elite"}, {"name": "Post-Trauma Muscle Preservation Protocol", "duration": "8 Weeks", "intensity": "Clinical"}, {"name": "Ultra-Endurance Hydration & Electrolyte Timing", "duration": "6 Weeks", "intensity": "Pro"}]'::jsonb,
    '[{"author": "Tyler Knox (Ironman Competitor)", "rating": 5, "comment": "Shaved 22 minutes off my Kona triathlon split purely from Sarah''s intra-race fueling protocol.", "date": "2 weeks ago"}, {"author": "Rachel Adams (CrossFit Games Athlete)", "rating": 5, "comment": "Zero digestive fatigue during multi-event weekends. Unmatched scientific rigor.", "date": "1 month ago"}]'::jsonb
),
(
    'marcus-vance',
    'Marcus Vance, MS, CSCS',
    'Director of Hypertrophy & Strength Bioenergetics',
    'Muscle Hypertrophy & Recomposition',
    '9+ Years',
    4.95,
    198,
    1100,
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80',
    'Master of Science in Exercise Physiology. Marcus engineered custom hypertrophy fueling blueprints for IFBB Pro League competitors and powerlifters across the globe.',
    '["M.S. Exercise Physiology (Penn State)", "CSCS (NSCA)", "Precision Nutrition Level 2 Master Coach"]'::jsonb,
    'Hypertrophy is a biological equation. Anabolic stimulus without precise caloric and amino-acid surplus is wasted energy.',
    '[{"name": "Calculated Mass Accretion (Hypertrophy Max)", "duration": "16 Weeks", "intensity": "Heavy"}, {"name": "Competition Peak Week Dehydration/Carb Load", "duration": "4 Weeks", "intensity": "Extreme"}]'::jsonb,
    '[{"author": "Brandon Cole", "rating": 5, "comment": "Gained 14 lbs of lean tissue while keeping waist circumference unchanged over 20 weeks.", "date": "3 days ago"}]'::jsonb
),
(
    'elena-rostova',
    'Dr. Elena Rostova, PhD',
    'Lead Metabolic Biochemist',
    'Metabolic Flexibility & Fat Oxidation',
    '14+ Years',
    4.88,
    164,
    920,
    'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=1200&q=80',
    'Author of 20+ peer-reviewed metabolic studies. Dr. Rostova architects fat loss protocols for fighters cutting weight and executives needing relentless mental stamina.',
    '["PhD in Nutritional Biochemistry (Oxford)", "Registered Dietitian Nutritionist (RDN)", "Functional Diagnostic Nutrition Practitioner (FDN-P)"]'::jsonb,
    'Turn your body into a metabolic furnace by aligning nutrient density with circadian rhythms and hormone profiles.',
    '[{"name": "Accelerated Lipid Oxidation & Fasted Fueling", "duration": "8 Weeks", "intensity": "Rigorous"}, {"name": "Circadian Fasting & Insulin Sensitivity Reset", "duration": "6 Weeks", "intensity": "Moderate"}]'::jsonb,
    '[{"author": "David S. (CEO)", "rating": 5, "comment": "Dr. Elena unlocked 14-hour steady focus with zero afternoon energy crashes.", "date": "Just now"}]'::jsonb
);

-- Seed Active Demo Users (Alex Vance and Admin Master)
INSERT INTO users (email, name, membership, member_since, age, weight, height, target_weight, daily_calories_target, protein_target, carbs_target, fats_target, water_target_oz, water_consumed_oz, assigned_nutritionist_id, active_plan, role)
VALUES 
(
    'alex.vance@nutrifuel.io',
    'Alex Vance',
    'Elite Tier',
    'March 2024',
    28,
    185,
    '6''1"',
    178,
    2850,
    220,
    280,
    70,
    128,
    96,
    'sarah-jenkins',
    'Sports Nutrition Elite (Week 6 of 12)',
    'USER'
),
(
    'admin@nutrifuel.io',
    'Admin Master',
    'Admin Level',
    'January 2024',
    35,
    180,
    '6''0"',
    180,
    2200,
    180,
    200,
    60,
    128,
    64,
    NULL,
    'None',
    'ADMIN'
),
-- Seed other demo users for admin dashboard
('rachel.adams@crossfit.com', 'Rachel Adams', 'Elite Tier', 'April 2024', 26, 145, '5''6"', 140, 2400, 160, 280, 60, 128, 100, 'marcus-vance', 'Sports Nutrition Elite', 'USER'),
('tknox@triathlon.org', 'Tyler Knox', 'Basic Tier', 'May 2024', 31, 165, '5''11"', 162, 3200, 150, 450, 75, 140, 120, 'sarah-jenkins', 'Hypertrophy Blueprint', 'USER'),
('elena.g@marathon.io', 'Elena Gomez', 'Clinical Tier', 'June 2024', 42, 138, '5''4"', 135, 1800, 110, 200, 50, 96, 64, 'elena-rostova', 'Diabetic Meal Plans', 'USER'),
('dchang@mma.com', 'David Chang', 'Ultimate Tier', 'July 2024', 24, 155, '5''8"', 145, 2600, 180, 200, 70, 128, 128, 'marcus-vance', 'Pro Competition Prep', 'USER');

-- Seed Meals for Alex Vance
INSERT INTO meals (user_email, name, time, calories, protein, carbs, fats, completed)
VALUES 
('alex.vance@nutrifuel.io', 'Meal 1: High-Density Egg White & Oat Scramble', '7:30 AM', 620, 48, 65, 14, true),
('alex.vance@nutrifuel.io', 'Meal 2: Pre-Workout Whey & Wild Blueberry Puree', '11:00 AM', 480, 42, 58, 6, true),
('alex.vance@nutrifuel.io', 'Meal 3: Post-Workout Flank Steak & Jasmine Rice', '2:30 PM', 740, 60, 75, 18, true),
('alex.vance@nutrifuel.io', 'Meal 4: Wild Salmon, Quinoa & Steamed Greens', '6:30 PM', 680, 52, 55, 22, false),
('alex.vance@nutrifuel.io', 'Meal 5: Micellar Casein & Almond Butter Sludge', '9:30 PM', 330, 38, 12, 10, false);

-- Seed Bookings
INSERT INTO bookings (id, user_email, nutritionist_id, type, date, time, goals, status)
VALUES 
('BK-8902', 'alex.vance@nutrifuel.io', 'sarah-jenkins', 'Video Call', 'Thursday, Oct 24, 2024', '02:00 PM EST', 'Targeting lean hypertrophy with carb cycling around 6 AM workouts.', 'Confirmed');

-- Seed Invoices for Alex Vance
INSERT INTO invoices (id, user_email, date, plan, amount, status, method)
VALUES 
('INV-2024-0089', 'alex.vance@nutrifuel.io', 'Aug 01, 2024', 'Sports Nutrition Elite (Monthly)', '$249.00', 'PAID', '•••• 4242 (Visa)'),
('INV-2024-0062', 'alex.vance@nutrifuel.io', 'Jul 01, 2024', 'Sports Nutrition Elite (Monthly)', '$249.00', 'PAID', '•••• 4242 (Visa)'),
('INV-2024-0041', 'alex.vance@nutrifuel.io', 'Jun 01, 2024', 'Sports Nutrition Elite (Monthly)', '$249.00', 'PAID', '•••• 4242 (Visa)'),
('INV-2024-0019', 'alex.vance@nutrifuel.io', 'May 01, 2024', 'Hypertrophy Blueprint (Monthly)', '$179.00', 'PAID', '•••• 4242 (Visa)'),
('INV-2024-0005', 'alex.vance@nutrifuel.io', 'Apr 01, 2024', 'Consultation Initial Assessment', '$95.00', 'PAID', '•••• 4242 (Visa)');
